version: '3'

volumes:
  pg-data:
  redis-data:

services:
  db:
    image: postgres:11-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '6379'
    sysctls:
      net.core.somaxconn: '1024'
    volumes:
      - redis-data:/data

  api:
    image: litewarp/patent_pro:api
    build:
      context: .
      dockerfile: ./rails_api/Dockerfile.dev
    depends_on:
      - db
      - redis
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/0
    ports:
      - 4002
    volumes:
      - ./rails_api:/dock_api

  app:
    image: litewarp/patent_pro:app
    build:
      context: .
      dockerfile: ./react_ui/Dockerfile.dev
    environment:
      - NODE_ENV=development
    ports:
      - 3000
    volumes:
      - ./react_ui:/dock_app

  web:
    image: litewarp/patent_pro:web
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:8001
