version: '3'

volumes:
  pg-data:
  redis-data:

services:
  db:
    image: postgres:11-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '6379'
    sysctls:
      net.core.somaxconn: '1024'
      vm.overcommit_memory: '1'
    volumes:
      - redis-data:/data

  api: &app_base
    image: litewarp/patent_pro:api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    depends_on:
      - db
      - redis
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_ENV=production
      - REDIS_URL=redis://redis:6379/0
      - MAGICK_MEMORY_LIMIT=512MiB
      - MAGICK_MAP_LIMIT=256MiB

  sidekiq:
    <<: *app_base
    command: ['bundle', 'exec', 'sidekiq', '-c', '5']
    ports: []

  web:
    image: litewarp/patent_pro:web
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - 80:8001
