version: '3'

volumes:
  pg-data:
  redis-data:

services:
  db:
    image: postgres:11-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '6379'
    sysctls:
      net.core.somaxconn: '1024'
    volumes:
      - redis-data:/data

  api: &app_base
    image: litewarp/patent_pro:api_dev
    build:
      context: .
      dockerfile: ./api/Dockerfile.dev
    depends_on:
      - db
      - redis
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/0
      - MAGICK_MEMORY_LIMIT=512MiB
      - MAGICK_MAP_LIMIT=256MiB
    ports:
      - 4002
    volumes:
      - ./api:/dock_api

  sidekiq:
    <<: *app_base
    command: ['bundle', 'exec', 'sidekiq', '-c', '25']
    ports: []

  app:
    image: litewarp/patent_pro:app_dev
    build:
      context: .
      dockerfile: ./app/Dockerfile.dev
    environment:
      - NODE_ENV=development
    ports:
      - 3000
    volumes:
      - ./app:/dock_app

  web:
    image: litewarp/patent_pro:web_dev
    build:
      context: .
      dockerfile: ./web/Dockerfile.dev
    ports:
      - 80:8001
