amazon:
  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  bucket: litewarp-s3
  region: us-west-2
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  service: S3
local:
  root: <%= Rails.root.join("storage") %>
  service: Disk
test:
  root: <%= Rails.root.join("tmp/storage") %>
  service: Disk
