source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem 'bootsnap', '>= 1.1.0', require: false
gem 'rails', '~> 5.2.3'
# web server
gem 'puma', '~> 3.11'
# database
gem 'pg'
gem 'pg_search'

# files and images
gem 'aws-sdk-s3'
gem 'docsplit'
gem 'mini_magick', '~> 4.8'

# JSON API
gem 'graphiti-rails'
gem 'graphiti_spec_helpers'
gem 'kaminari'
gem 'responders'

# external API
gem 'mechanize'
gem 'nokogiri'

# workers
gem 'sidekiq'
gem 'sidekiq-cron'
gem 'sidekiq-unique-jobs'

# middelware
gem 'awesome_rails_console'
gem 'rack'
gem 'rack-cors'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'foreman'
end

group :development do
  gem 'hirb'
  gem 'hirb-unicode-steakknife', require: 'hirb-unicode'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'pry-byebug'
  gem 'rubocop', require: false
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
